keys:
  - &makefu F7B8DCE46BC6B0A8F95477C8563B8DFE2A0E2029
  - &x_host age1hqe5hs2jz2fk5zvw346ajhwlagkheunacahpu42uruxu0nlnwy7qn9q5k6
  - &tsp_host age1p7jqdpahxtf7j70kmzy7vg6za7wg63u6sq7ywuw6qkw0qek395nq5kyzae
  - &gum_host age1yvcv4s355qzm2a3yuk4a79pfnc3u3kc4uxy0yj9js0qnjdvt05lst7vm07
  - &omo_host age1rkdqyfk4txy87f8j7y673u93td4chj2x8adqdetvyvhk59c4699ssn3den
  - &wbob_host age1pdumzc767t387n25kccc949yw9n5m2gzemgzad4ts8pvpcpmkvqqc8m3kj
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *tsp_host
      - *x_host
  # host secrets
  - path_regex: secrets/x.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *x_host
  - path_regex: secrets/tsp.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *tsp_host
  - path_regex: secrets/gum.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *gum_host
  - path_regex: secrets/omo.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *omo_host
  - path_regex: secrets/wbob.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *wbob_host
